SELECT ('/home/grep/src/'||B.BOARD_ID||'/'||B.FILE_ID||B.FILE_NAME||B.FILE_EXT) AS FILE_PATH 
-- 문자열을 3개 이상 합치는건 CONCAT 함수보다 ||이 간편함.
FROM USED_GOODS_BOARD A, USED_GOODS_FILE B
WHERE A.BOARD_ID = B.BOARD_ID 
AND A.VIEWS=(SELECT MAX(VIEWS)FROM USED_GOODS_BOARD) 
ORDER BY B.FILE_ID DESC;