-- 코드를 입력하세요

SELECT TITLE, b.BOARD_ID, REPLY_ID, r.WRITER_ID, r.CONTENTS, TO_CHAR(r.CREATED_DATE,'YYYY-MM-DD' ) AS CREATED_DATE 
FROM USED_GOODS_BOARD b, USED_GOODS_REPLY r 
WHERE b.BOARD_ID=r.BOARD_ID AND TO_CHAR(b.CREATED_DATE,'YYYY-MM')='2022-10'  
ORDER BY CREATED_DATE, TITLE ;