-- 코드를 입력하세요
SELECT I.INGREDIENT_TYPE,
SUM(F.TOTAL_ORDER)AS TOTAL_ORDER 
FROM FIRST_HALF F, ICECREAM_INFO I WHERE F.FLAVOR=I.FLAVOR GROUP BY INGREDIENT_TYPE

--SELECT B.INGREDIENT_TYPE AS INGREDIENT_TYPE , SUM(A.TOTAL_ORDER) AS TOTAL_ORDER FROM FIRST_HALF  A , ICECREAM_INFO  B WHERE 1=1 AND   A.FLAVOR = B.FLAVOR GROUP BY INGREDIENT_TYPE