/*SELECT COUNT(*) AS FISH_COUNT  FROM FISH_INFO i
LEFT JOIN FISH_NAME_INFO n
ON i.FISH_TYPE=n.FISH_TYPE
WHERE i.FISH_TYPE IN(0,1);
*/
/*결과는 같다 생각하는데 왜 안될까*/

SELECT COUNT(*) AS FISH_COUNT FROM FISH_INFO i
LEFT JOIN FISH_NAME_INFO n
ON i.FISH_TYPE=n.FISH_TYPE
WHERE n.FISH_NAME IN('BASS','SNAPPER');
