-- 코드를 입력하세요
SELECT DISTINCT CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR, CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
WHERE CAR.CAR_ID=HISTORY.CAR_ID AND CAR.CAR_TYPE='세단' AND TO_CHAR(HISTORY.START_DATE,'MM')='10'
ORDER BY CAR.CAR_ID DESC;